// Code generated by protoc-gen-go.
// source: url.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	url.proto

It has these top-level messages:
	URLProto
*/
package main

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type URLProto struct {
	Username string `protobuf:"bytes,1,opt" json:"Username,omitempty"`
	Url      string `protobuf:"bytes,2,opt" json:"Url,omitempty"`
}

func (m *URLProto) Reset()         { *m = URLProto{} }
func (m *URLProto) String() string { return proto.CompactTextString(m) }
func (*URLProto) ProtoMessage()    {}
