// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	UserProto
*/
package main

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type UserProto struct {
	Username string `protobuf:"bytes,1,opt" json:"Username,omitempty"`
	Name     string `protobuf:"bytes,2,opt" json:"Name,omitempty"`
}

func (m *UserProto) Reset()         { *m = UserProto{} }
func (m *UserProto) String() string { return proto.CompactTextString(m) }
func (*UserProto) ProtoMessage()    {}
